name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit username
        env:
          COMMITTER_USERNAME: ${{ toJson(github.event.commits.*.author.username) }}
        run: echo "$COMMITTER_USERNAME"
      - name: commit url
        env: 
            COMMITS_URL: ${{ toJson(github.event.commits.*.url) }}
        run: echo "$COMMITS_URL"
